SOURCES = startup.s 
SOURCES += main.cc
SOURCES += test_init.cc

SOURCES += ../drivers/init.cc
SOURCES += ../drivers/serial.cc
SOURCES += ../drivers/print.cc

INCLUDES  = -I.
INCLUDES += -I..

include ../makefile-common.mk

