SOURCES = startup.s 
SOURCES += main.cc
SOURCES += test_init.cc

SOURCES += ../drivers/init.cc
SOURCES += ../drivers/serial.cc
SOURCES += ../drivers/print.cc

INCLUDES  = -I.
INCLUDES += -I..

INCLUDES += -I../drivers/mdrivlib/target/rk3566
INCLUDES += -I../drivers/mdrivlib/target/aarch64

include ../makefile-common.mk

