SOURCES = startup.s 
SOURCES += main.cc
SOURCES += test_init.cc

SOURCES += ../drivers/init.cc
SOURCES += ../drivers/serial.cc

INCLUDES  = -I.
INCLUDES += -I../drivers

include ../makefile-common.mk

