SOURCES = startup.s 
SOURCES += main.cc
SOURCES += mmu.cc

SOURCES += ../drivers/init.cc
SOURCES += ../drivers/serial.cc

INCLUDES  = -I.
INCLUDES += -I../drivers
INCLUDES += -I../lib

OPTFLAG = -O3

include ../makefile-common.mk

