SOURCES = startup.s 
SOURCES += main.cc
SOURCES += mmu.cc
SOURCES += aarch64.c

SOURCES += ../drivers/init.cc
SOURCES += ../drivers/serial.cc

INCLUDES  = -I.
INCLUDES += -I../drivers

OPTFLAG = -O3

include ../makefile-common.mk

